[versions]
jacksonDatabind = "2.20.1"
jacksonJsr310 = "2.20.1"
okhttp = "5.3.2"
dagger = "2.59.1"
mirror = "5.0.5"
reconstruct = "1.3.27"
vineflower = "1.11.2"
slf4j = "2.0.17"
picocli = "4.7.7"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jacksonJsr310" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
mirror = { module = "mx.kenzie:mirror", version.ref = "mirror" }
reconstruct-common = { module = "io.github.lxgaming:reconstruct-common", version.ref = "reconstruct" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
